### PR TITLE
Release v0.5.0

### PR DESCRIPTION
**Pull request by mcrumm**
`CHANGELOG.md` is missing the release date - could you please include it when you merge/publish?

Thanks!!

### CODE REVIEW

**Comment by wojtekmach** [comment]
v0.5 is out, thanks!

**Comment by mcrumm** [comment]
@wojtekmach Would you mind publishing a docs update?  I added notes on Batching to the primary docs, and updated both examples with the proper shape of the start_link options.  Thanks!

**Comment by wojtekmach** [comment]
Done, thank you! <3

--
Wojtek Mach

**Comment by mcrumm** [comment]
Thank **you**, sir!

**Pull request merged**
